// Code generated by "stringer --type GameState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[loading-0]
	_ = x[ready-1]
	_ = x[launching-2]
}

const _GameState_name = "loadingreadylaunching"

var _GameState_index = [...]uint8{0, 7, 12, 21}

func (i GameState) String() string {
	if i < 0 || i >= GameState(len(_GameState_index)-1) {
		return "GameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
