// Code generated by "stringer --type GameState"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[preparing-0]
	_ = x[ready-1]
	_ = x[running-2]
	_ = x[paused-3]
}

const _GameState_name = "preparingreadyrunningpaused"

var _GameState_index = [...]uint8{0, 9, 14, 21, 27}

func (i GameState) String() string {
	if i < 0 || i >= GameState(len(_GameState_index)-1) {
		return "GameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
